export const projects = [
    {
      title: 'GPT-3 Website',
      description: "Generative Pre-trained Transformer 3 (GPT-3) is an autoregressive language model that uses deep learning to produce human-like text. Given an initial text as prompt, it will produce text that continues the prompt.",
        image: '/images/gpt3-01.png',
        tags: ['React', 'JavaScript'],
      source: 'https://gpt-3-website-beta.vercel.app/',
      visit: 'https://github.com/muliasw12/GPT3-Website',
      id: 0,
    },
    {
      title: 'Gericht Restaurant',
      description:"Technology that continues to develop makes food entrepreneurs more innovative in promoting their wares. One of them is by using the website. In this project I created a restaurant landing page using React.",
      image: '/images/gericht-restaurant.png',
      tags: ['React', 'JavaScript'],
      source: 'https://gericht-restaurant-website-bay.vercel.app/',
      visit: 'https://github.com/muliasw12/Gericht-Restaurant-Website',
      id: 1,
    },
    {
      title: 'Galleria Slideshow Site',
      description: "The Galleria Slideshow Site is a stunning and interactive web application built using Vue.js, a progressive JavaScript framework. This project aims to create a visually appealing and seamless slideshow site where users can showcase and explore captivating image galleries in an engaging and user-friendly manner.",
        image: '/images/gallery.png',
        tags: ['Vue js', 'JavaScript', 'HTML'],
      source: 'https://galleria-slideshow-site-ochre.vercel.app/',
      visit: 'https://github.com/muliasw12/galleria-slideshow-site',
      id: 2,
    },
    {
      title: 'Kanban Management Task App',
      description: "The Kanban Management Task App is a powerful and intuitive project management tool designed to enhance productivity and streamline task management. Built on the Kanban methodology, this app provides teams and individuals with a visual framework to organize, track, and prioritize tasks in a flexible and efficient manner.",
      image: '/images/kanban.png',
      tags: ['React', 'Redux', 'SCSS'],
      source: 'https://kanban-project-drab.vercel.app/',
      visit: 'https://github.com/muliasw12/kanban-project',
      id: 3,
    },
    {
      title: 'Responsive e-commerce Product Page',
      description: "This is a solution to the E-commerce product page challenge on Frontend Mentor. Frontend Mentor challenges help you improve your coding skills by building realistic projects. This project built with Semantic HTML5 markup, CSS custom properties, Flexbox, CSS Grid, and Mobile-first workflow",
      image: '/images/ecommerce-frontend-mentor.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
      source: 'https://responsive-ecommerce-product-page.vercel.app/',
      visit: 'https://github.com/muliasw12/Responsive-ecommerce-product-page',
      id: 4,
    },
    {
      title: 'Shortly URL Landing Page',
      description: "This is a solution to the Shortly URL landing page challenge on Frontend Mentor. This project integrate with the shrtcode URL shortening API and play with browser storage in this landing page. View the optimal layout for the site depending on their device's screen size. This page can be shorten any valid URL. See a list of their shortened links, even after refreshing the browser.",
      image: '/images/shortly-url.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
      source: 'https://url-shortening-api-landing-page-rouge.vercel.app/',
      visit: 'https://github.com/muliasw12/URL-shortening-API-landing-page',
      id: 5,
    },
  ];
  
  export const TimeLineData = [
    { year: 2020, text: 'Worked as a Physics Tutor at Beta Belajar', },
    { year: 2021, text: 'Student Internship at KAIST', },
    { year: 2022, text: 'Worked as a Teaching Assistant and Laboratory Assistant at ITB', },
    { year: 2023, text: 'Front End Developer at Wistkey', },
  ];
