export const projects = [
    {
      title: 'Car Showcase',
      description: "A showcase displayed for several types of cars where the data used comes from an API. The website is built using Next.js TypeScript, and Tailwind CSS is used for styling.",
        image: '/images/car-showcase.png',
        tags: ['Next.js', 'Typescript', 'Tailwind CSS'],
      source: 'https://car-showcase-tau-drab.vercel.app/',
      visit: 'https://github.com/muliasw12/car-showcase',
      id: 0,
    },
    {
      title: 'Travel App Landing Page',
      description:"Created responsive traveling application website using Typescript and Tailwind css",
      image: '/images/travel-app.png',
      tags: ['Next.js', 'Typescript', 'Tailwind CSS'],
      source: 'https://travel-app-landing-page-six.vercel.app/',
      visit: 'https://github.com/muliasw12/travel-app-landing-page',
      id: 1,
    },
    {
      title: 'Galleria Slideshow Site',
      description: "The Galleria Slideshow Site is a stunning and interactive web application built using Vue.js, a progressive JavaScript framework. This project aims to create a visually appealing and seamless slideshow site where users can showcase and explore captivating image galleries in an engaging and user-friendly manner.",
        image: '/images/gallery.png',
        tags: ['Vue js', 'JavaScript', 'HTML'],
      source: 'https://galleria-slideshow-site-ochre.vercel.app/',
      visit: 'https://github.com/muliasw12/galleria-slideshow-site',
      id: 2,
    },
    {
      title: 'Kanban Management Task App',
      description: "The Kanban Management Task App is a powerful and intuitive project management tool designed to enhance productivity and streamline task management. Built on the Kanban methodology, this app provides teams and individuals with a visual framework to organize, track, and prioritize tasks in a flexible and efficient manner.",
      image: '/images/kanban.png',
      tags: ['React', 'Redux', 'SCSS'],
      source: 'https://kanban-project-drab.vercel.app/',
      visit: 'https://github.com/muliasw12/kanban-project',
      id: 3,
    },
    {
      title: 'Responsive e-commerce Product Page',
      description: "This is a solution to the E-commerce product page challenge on Frontend Mentor. Frontend Mentor challenges help you improve your coding skills by building realistic projects. This project built with Semantic HTML5 markup, CSS custom properties, Flexbox, CSS Grid, and Mobile-first workflow",
      image: '/images/ecommerce-frontend-mentor.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
      source: 'https://responsive-ecommerce-product-page.vercel.app/',
      visit: 'https://github.com/muliasw12/Responsive-ecommerce-product-page',
      id: 4,
    },
    {
      title: 'Shortly URL Landing Page',
      description: "This is a solution to the Shortly URL landing page challenge on Frontend Mentor. This project integrate with the shrtcode URL shortening API and play with browser storage in this landing page. View the optimal layout for the site depending on their device's screen size. This page can be shorten any valid URL. See a list of their shortened links, even after refreshing the browser.",
      image: '/images/shortly-url.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
      source: 'https://url-shortening-api-landing-page-rouge.vercel.app/',
      visit: 'https://github.com/muliasw12/URL-shortening-API-landing-page',
      id: 5,
    },
  ];
  
  export const TimeLineData = [
    { year: 2021, text: 'Student Internship at KAIST', },
    { year: 2022, text: 'Graduated from Bandung Institute of Technology B.Sc of Physics', },
    { year: 2023, text: 'Jr. Software Developer at Wistkey', },
    { year: 2024, text: 'Full Stack Developer at BLKP Group', },
  ];
